version: "3"

services:

  db_mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    env_file:
      - ./config/mysql.env

  cache_redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file:
      - ./config/redis.env
    volumes:
      - ./data/cache:/data
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD}"

  app_spring:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - ./config/mysql.env
      - ./config/redis.env
    depends_on:
      - db_mysql