INSERT INTO MEME(TITLE, IMAGE_URL, VIEW_COUNT, CREATE_DATE) VALUES('안녕1', 'https://s3.us-west-2.amazonaws.com/secure.notion-static.com/cad31965-0c62-44ca-ae45-4e050d4ec9b8t', 1, now());
INSERT INTO MEME(TITLE, IMAGE_URL, VIEW_COUNT, CREATE_DATE) VALUES('안녕9', 'https://s3.us-west-2.amazonaws.com/secure.notion-static.com/cad31965-0c62-44ca-ae45-4e050d4ec9b8t', 9, now());
INSERT INTO MEME(TITLE, IMAGE_URL, VIEW_COUNT, CREATE_DATE) VALUES('안녕4', 'https://s3.us-west-2.amazonaws.com/secure.notion-static.com/cad31965-0c62-44ca-ae45-4e050d4ec9b8t', 4, now());
INSERT INTO MEME(TITLE, IMAGE_URL, VIEW_COUNT, CREATE_DATE) VALUES('안녕2', 'https://s3.us-west-2.amazonaws.com/secure.notion-static.com/cad31965-0c62-44ca-ae45-4e050d4ec9b8t', 2, now());

INSERT INTO CATEGORY(NAME) VALUES('카테고리 명1');
INSERT INTO CATEGORY(NAME) VALUES('카테고리 명2');

INSERT INTO TAG(NAME, VIEW_COUNT, CATEGORY_ID) VALUES('태그 제목1', 1, 1);
INSERT INTO TAG(NAME, VIEW_COUNT, CATEGORY_ID) VALUES('태그 제목2', 10, 2);
INSERT INTO TAG(NAME, VIEW_COUNT, CATEGORY_ID) VALUES('태그 제목3', 14, 2);
INSERT INTO TAG(NAME, VIEW_COUNT, CATEGORY_ID) VALUES('태그 제목4', 6, 1);
INSERT INTO TAG(NAME, VIEW_COUNT, CATEGORY_ID) VALUES('태그 제목5', 11, 1);


INSERT INTO MEME_TAG(MEME_ID, TAG_ID) VALUES(1, 1);
INSERT INTO MEME_TAG(MEME_ID, TAG_ID) VALUES(2, 1);
INSERT INTO MEME_TAG(MEME_ID, TAG_ID) VALUES(1, 2);


