INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('php', 'php 개발자 밈입니다.', 115, 1, DATE_ADD(NOW(), INTERVAL 1 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('에타 시험기간', '에타 시험기간 밈 모음입니다', 93, 2, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('페페', '초록 개구리 페페 밈입니다.', 45, 3, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('평생 입 다물게 해줄까?', '박명수가 무한도전 123화에서 한 말', 445, 4, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('그래도... 일은 해야지...', '무한도전 중 박명수 어록 중 하나', 455, 5, DATE_ADD(NOW(), INTERVAL 26 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('아~', '무한도전 박명수 하품', 101, 5, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('종잡을 수 없는 흐름에 다들 소름', '무한도전 양세형 소름', 102, 6, DATE_ADD(NOW(), INTERVAL 19 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('요만큼도 없다', '무한도전 유재석 밈', 103, 7, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('속이 속이 아니잖아요...', '무한도전 유재석 밈', 104, 8, DATE_ADD(NOW(), INTERVAL 12 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('사이버머니 조심해요', '무한도전 유재석 밈', 105, 39, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('재수 없으니까 가만히 좀', '무한도전 박명수 밈', 106, 11, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('입 좀 다물고 기다리시죠?', '무한도전 유재석 밈', 107, 18, DATE_ADD(NOW(), INTERVAL 16 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('조용히 하지 못할까 이 요망한 것!', '무한도전 유재석 밈', 108, 127, DATE_ADD(NOW(), INTERVAL 10 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('좀 이해해주십시오! 화내서 미안합니다', '무한도전 유재석 밈', 109, 98, now());
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('사기꾼이에요?', '무한도전 유재석 밈', 110, 182, DATE_ADD(NOW(), INTERVAL 36 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('세월을 우리만 맞은 듯', '무한도전 유재석 밈', 110, 42, DATE_ADD(NOW(), INTERVAL 5 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('두 개를 가질 수는 없겠더라고...', '무한도전 유재석 밈', 111, 198, DATE_ADD(NOW(), INTERVAL 3 DAY));
INSERT INTO meme(name, description, view_count, share_count, created_date) VALUES('일이 많아!', '무한도전 유재석 밈', 112, 32, DATE_ADD(NOW(), INTERVAL 1 MONTH));

INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/1.png', 960, 987, 1);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/2.png', 517, 706, 2);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/3.png', 466, 631, 2);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/4.png', 488, 566, 2);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/5.png', 225, 225, 3);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/6.png', 686, 377, 4);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/7.png', 609, 609, 5);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/8.png', 591, 746, 6);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/9.png', 1200, 675, 7);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/10.png', 1920, 1080, 8);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/11.png', 1280, 720, 9);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/12.png', 330, 153, 10);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/13.png', 320, 287, 11);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/14.png', 600, 457, 12);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/15.png', 400, 403, 13);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/16.png', 800, 450, 14);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/17.png', 600, 471, 15);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/18.png', 1200, 1200, 16);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/19.png', 600, 659, 17);
INSERT INTO image(image_url, width, height, meme_id) VALUES('https://yappmemebucket.s3.ap-northeast-2.amazonaws.com/memes/images/20.png', 600, 476, 18);

INSERT INTO category(name, priority) VALUES('직업', 100);
INSERT INTO category(name, priority) VALUES('캐릭터', 200);
INSERT INTO category(name, priority) VALUES('예능', 300);
INSERT INTO category(name, priority) VALUES('인물', 300);
INSERT INTO category(name, priority) VALUES('감정', 400);
INSERT INTO category(name, priority) VALUES('기타', 500);

INSERT INTO tag(name, view_count, category_id) VALUES('개발자', 52, 1);
INSERT INTO tag(name, view_count, category_id) VALUES('에브리타임', 49, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('시험기간', 34, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('페페', 26, 2);
INSERT INTO tag(name, view_count, category_id) VALUES('유머', 140, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('박명수', 140, 4);
INSERT INTO tag(name, view_count, category_id) VALUES('서러움', 140, 5);
INSERT INTO tag(name, view_count, category_id) VALUES('분노', 140, 5);
INSERT INTO tag(name, view_count, category_id) VALUES('무한도전', 220, 3);
INSERT INTO tag(name, view_count, category_id) VALUES('무', 11, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('무시', 18, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('무한', 12, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('무한도', 13, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('무전', 18, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('무한전', 8, 6);
INSERT INTO tag(name, view_count, category_id) VALUES('무도전', 2, 6);


INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(1, 1);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(1, 5);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(2, 2);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(2, 3);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(2, 5);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(3, 4);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(4, 5);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(4, 6);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(4, 8);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(4, 9);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(5, 5);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(5, 6);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(5, 7);
INSERT INTO meme_tag(MEME_ID, TAG_ID) VALUES(5, 9);

INSERT INTO adjective(word) VALUES ('거절하는');
INSERT INTO adjective(word) VALUES ('거짓말하는');
INSERT INTO adjective(word) VALUES ('걱정하는');
INSERT INTO adjective(word) VALUES ('경계하는');
INSERT INTO adjective(word) VALUES ('공부하는');
INSERT INTO adjective(word) VALUES ('과몰입하는');
INSERT INTO adjective(word) VALUES ('관심없는');
INSERT INTO adjective(word) VALUES ('귀여운');
INSERT INTO adjective(word) VALUES ('귀찮은');
INSERT INTO adjective(word) VALUES ('기대하는');
INSERT INTO adjective(word) VALUES ('기쁜');
INSERT INTO adjective(word) VALUES ('노력하는');
INSERT INTO adjective(word) VALUES ('놀고싶은');
INSERT INTO adjective(word) VALUES ('놀란');
INSERT INTO adjective(word) VALUES ('눈치보는');
INSERT INTO adjective(word) VALUES ('늦은');
INSERT INTO adjective(word) VALUES ('단호한');
INSERT INTO adjective(word) VALUES ('당연한');
INSERT INTO adjective(word) VALUES ('대답하는');
INSERT INTO adjective(word) VALUES ('더운');
INSERT INTO adjective(word) VALUES ('따스한눈빛인');
INSERT INTO adjective(word) VALUES ('먹부림하는');
INSERT INTO adjective(word) VALUES ('멍청한');
INSERT INTO adjective(word) VALUES ('믿기지않는');
INSERT INTO adjective(word) VALUES ('바쁜');
INSERT INTO adjective(word) VALUES ('배고픈');
INSERT INTO adjective(word) VALUES ('배부른');
INSERT INTO adjective(word) VALUES ('부끄러운');
INSERT INTO adjective(word) VALUES ('부탁하는');
INSERT INTO adjective(word) VALUES ('비꼬는');
INSERT INTO adjective(word) VALUES ('빈둥거리는');
INSERT INTO adjective(word) VALUES ('빈정거리는');
INSERT INTO adjective(word) VALUES ('사과하는');
INSERT INTO adjective(word) VALUES ('사진찍는');
INSERT INTO adjective(word) VALUES ('살찌는');
INSERT INTO adjective(word) VALUES ('세뱃돈받는');
INSERT INTO adjective(word) VALUES ('속박되는');
INSERT INTO adjective(word) VALUES ('시원한');
INSERT INTO adjective(word) VALUES ('심심한');
INSERT INTO adjective(word) VALUES ('아픈');
INSERT INTO adjective(word) VALUES ('애교부리는');
INSERT INTO adjective(word) VALUES ('억울한');
INSERT INTO adjective(word) VALUES ('여행가고싶은');
INSERT INTO adjective(word) VALUES ('예민한');
INSERT INTO adjective(word) VALUES ('외로운');
INSERT INTO adjective(word) VALUES ('외면하는');
INSERT INTO adjective(word) VALUES ('욕하는');
INSERT INTO adjective(word) VALUES ('운동하는');
INSERT INTO adjective(word) VALUES ('울컥하는');
INSERT INTO adjective(word) VALUES ('웃긴');
INSERT INTO adjective(word) VALUES ('웃참하는');
INSERT INTO adjective(word) VALUES ('의문스러운');
INSERT INTO adjective(word) VALUES ('인사하는');
INSERT INTO adjective(word) VALUES ('인정하는');
INSERT INTO adjective(word) VALUES ('일어나는');
INSERT INTO adjective(word) VALUES ('일침놓는');
INSERT INTO adjective(word) VALUES ('일하러가기싫은');
INSERT INTO adjective(word) VALUES ('일하는');
INSERT INTO adjective(word) VALUES ('입대하는');
INSERT INTO adjective(word) VALUES ('자만하는');
INSERT INTO adjective(word) VALUES ('자상한');
INSERT INTO adjective(word) VALUES ('잠오는');
INSERT INTO adjective(word) VALUES ('잠자는');
INSERT INTO adjective(word) VALUES ('졸린');
INSERT INTO adjective(word) VALUES ('즐거운');
INSERT INTO adjective(word) VALUES ('지치는');
INSERT INTO adjective(word) VALUES ('차인');
INSERT INTO adjective(word) VALUES ('참교육하는');
INSERT INTO adjective(word) VALUES ('추운');
INSERT INTO adjective(word) VALUES ('축하하는');
INSERT INTO adjective(word) VALUES ('출발하는');
INSERT INTO adjective(word) VALUES ('춤추는');
INSERT INTO adjective(word) VALUES ('칭찬하는');
INSERT INTO adjective(word) VALUES ('콧물나는');
INSERT INTO adjective(word) VALUES ('쾌변하는');
INSERT INTO adjective(word) VALUES ('태세전환하는');
INSERT INTO adjective(word) VALUES ('퇴사하는');
INSERT INTO adjective(word) VALUES ('폭식하는');
INSERT INTO adjective(word) VALUES ('피곤한');
INSERT INTO adjective(word) VALUES ('하기싫은');
INSERT INTO adjective(word) VALUES ('허세부리는');
INSERT INTO adjective(word) VALUES ('헬스하는');
INSERT INTO adjective(word) VALUES ('호통치는');
INSERT INTO adjective(word) VALUES ('혼란스러운');
INSERT INTO adjective(word) VALUES ('화나는');
INSERT INTO adjective(word) VALUES ('회식하는');
INSERT INTO adjective(word) VALUES ('힘든');
INSERT INTO adjective(word) VALUES ('미안한');
INSERT INTO adjective(word) VALUES ('자신만만한');
INSERT INTO adjective(word) VALUES ('두려운');
INSERT INTO adjective(word) VALUES ('미운');
INSERT INTO adjective(word) VALUES ('당황한');
INSERT INTO adjective(word) VALUES ('측은한');
INSERT INTO adjective(word) VALUES ('상쾌한');
INSERT INTO adjective(word) VALUES ('실망하는');
INSERT INTO adjective(word) VALUES ('여유로운');

INSERT INTO Noun(word) VALUES ('ENFJ');
INSERT INTO Noun(word) VALUES ('ENFP');
INSERT INTO Noun(word) VALUES ('ENTJ');
INSERT INTO Noun(word) VALUES ('ENTP');
INSERT INTO Noun(word) VALUES ('ESFJ');
INSERT INTO Noun(word) VALUES ('ESFP');
INSERT INTO Noun(word) VALUES ('ESTJ');
INSERT INTO Noun(word) VALUES ('ESTP');
INSERT INTO Noun(word) VALUES ('INFJ');
INSERT INTO Noun(word) VALUES ('INFP');
INSERT INTO Noun(word) VALUES ('INTJ');
INSERT INTO Noun(word) VALUES ('INTP');
INSERT INTO Noun(word) VALUES ('ISFJ');
INSERT INTO Noun(word) VALUES ('ISFP');
INSERT INTO Noun(word) VALUES ('ISTJ');
INSERT INTO Noun(word) VALUES ('ISTP');
INSERT INTO Noun(word) VALUES ('거짓말쟁이');
INSERT INTO Noun(word) VALUES ('군인');
INSERT INTO Noun(word) VALUES ('귀요미');
INSERT INTO Noun(word) VALUES ('멍청이');
INSERT INTO Noun(word) VALUES ('직장인');
INSERT INTO Noun(word) VALUES ('집돌이');
INSERT INTO Noun(word) VALUES ('집순이');
INSERT INTO Noun(word) VALUES ('학생');
INSERT INTO Noun(word) VALUES ('헬린이');
INSERT INTO Noun(word) VALUES ('개발자');
INSERT INTO Noun(word) VALUES ('디자이너');
INSERT INTO Noun(word) VALUES ('밈쟁이');