ALTER TABLE MEME_TAG
DROP
FOREIGN KEY FKD3FKXMPUSGYFO3JLJ1XMSQ69B;

ALTER TABLE MEME_TAG
DROP
FOREIGN KEY FK9HO1AOM8WVYMJTUH46W1MRIVQ;

ALTER TABLE TAG
DROP
FOREIGN KEY FKRUOLOYH4BF4KDKO2CCV18XYYX;

DROP TABLE IF EXISTS CATEGORY;

DROP TABLE IF EXISTS MEME;

DROP TABLE IF EXISTS MEME_TAG;

DROP TABLE IF EXISTS TAG;