CREATE TABLE IF NOT EXISTS CATEGORY (
                          TAG_ID BIGINT NOT NULL AUTO_INCREMENT,
                          NAME VARCHAR(50) NOT NULL,
                          PRIMARY KEY (TAG_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MEME (
                      MEME_ID BIGINT NOT NULL AUTO_INCREMENT,
                      CREATE_DATE DATETIME(6),
                      MODIFIED_DATE DATETIME(6),
                      IMAGE_URL VARCHAR(1024) NOT NULL,
                      TITLE VARCHAR(100) NOT NULL,
                      VIEW_COUNT INTEGER,
                      PRIMARY KEY (MEME_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MEME_TAG (
                          MEME_TAG_ID BIGINT NOT NULL AUTO_INCREMENT,
                          MEME_ID BIGINT NOT NULL,
                          TAG_ID BIGINT NOT NULL,
                          PRIMARY KEY (MEME_TAG_ID)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TAG (
                     TAG_ID BIGINT NOT NULL AUTO_INCREMENT,
                     NAME VARCHAR(50) NOT NULL,
                     VIEW_COUNT INTEGER,
                     CATEGORY_ID BIGINT NOT NULL,
                     PRIMARY KEY (TAG_ID)
) ENGINE=INNODB;

ALTER TABLE MEME_TAG
    ADD CONSTRAINT FKD3FKXMPUSGYFO3JLJ1XMSQ69B
        FOREIGN KEY (MEME_ID)
            REFERENCES MEME (MEME_ID);

ALTER TABLE MEME_TAG
    ADD CONSTRAINT FK9HO1AOM8WVYMJTUH46W1MRIVQ
        FOREIGN KEY (TAG_ID)
            REFERENCES TAG (TAG_ID);

ALTER TABLE TAG
    ADD CONSTRAINT FKRUOLOYH4BF4KDKO2CCV18XYYX
        FOREIGN KEY (CATEGORY_ID)
            REFERENCES CATEGORY (TAG_ID);