spring:
  config:
    activate:
      on-profile: test

  datasource:
    # H2 DB를 인메모리 모드로 둔다.
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # 기본 계정이 sa에 비밀번호 없음이다.
    username: sa
    password:
    # DB 커넥션과 관련된 데이터 소스 설정이 완료된다.
    driver-class-name: org.h2.Driver

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      # 자동으로 테이블을 만들어주는 모드. create로 두면 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다.
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

  redis:
    host: localhost
    port: 6379
    password: redispw

  jwt:
    secret: "springtesttesttesttesttesttesttest"


# p6spy 적용
decorator:
  datasource:
    p6spy:
      enable-logging: true