spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memeserver
    username: yappuser
    password: yapppassword

  jpa:
    database: mysql
    hibernate:
      # 자동으로 테이블을 만들어주는 모드. create로 두면 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다.
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
#      schema-locations: classpath:sql/schema.sql

  redis:
    host: localhost
    port: 6379
    password: redispw

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
      base-path: "/system"
  endpoint:
    health:
      enabled: true
      show-details: always

# p6spy 적용
decorator:
  datasource:
    p6spy:
      enable-logging: true

# springdoc swagger
springdoc:
  api-docs:
    # JSON 제공 접속 path 설정
    path: /swagger/docs

  swagger-ui:
    # UI 제공 접속 path 설정
    path: /swagger/ui
    # Try it out 시 Request Duration 표시
    display-request-duration: true

  cache:
    # 캐시 비활성화 (로컬에서만 사용 권장)
    disabled: true

  # @ControllerAdvice 응답은 API 응답에 포함되지 않도록 설정
  override-with-generic-response: false