spring:
  datasource:
    # H2 DB를 인메모리 모드로 둔다.
    url: jdbc:h2:mem:testdb
    # 기본 계정이 sa에 비밀번호 없음이다.
    username: sa
    password:
    # DB 커넥션과 관련된 데이터 소스 설정이 완료된다.
    driver-class-name: org.h2.Driver

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      # 자동으로 테이블을 만들어주는 모드. create로 두면 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다.
      ddl-auto: create
    # 하이버네이트와 관련된 특정 프로퍼티를 사용할 수 있다.
    properties:
      hibernate:
        # SQL을 가독성 있게 출력한다.
        format_sql: true
        # ANSI SQL에 맞게 색을 칠해준다.
        highlight_sql: true

logging.level:
  # logger를 통해 하이버네이트 실행 SQL을 남긴다.
  org.hibernate.SQL: debug

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
      base-path: "/system"
  endpoint:
    health:
      enabled: true
      show-details: always