spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      poolName: Hikari
      maximum-pool-size: 20
      max-lifetime: 1800000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect

  redis:
    host: cache_redis
    port: 6379
    password: ${REDIS_PASSWORD}

  jwt:
    secret: ${SPRING_JWT_SECRET}


# p6spy 적용
decorator:
  datasource:
    p6spy:
      enable-logging: false