spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect

  redis:
    host: cache_redis
    port: 6379
    password: ${REDIS_PASSWORD}

  jwt:
    secret: ${SPRING_JWT_SECRET}


# p6spy 적용
decorator:
  datasource:
    p6spy:
      enable-logging: true